Code cleanup and development
osrep/Runaphys pull request #48
Opened 2020-08-19 10:28 UTC by pordaniel01

Some codesmells have been fixed. hdf5 components added. Function input checks have been added.

2020-08-19 10:34 UTC, olaszsoma requested changes
Fix the messages commented on. It might be cleaner if the check functions were put in separate functions instead of adding if statements in every function. This should be discussed with Gergo.

2020-08-19 10:34 UTC, olaszsoma commented on CMakeLists.txt
> +message($)
This message is unnecessary.

2020-08-19 10:34 UTC, olaszsoma commented on src/CMakeLists.txt
> +message(${SOURCE_FILES})
Delete this message.

2020-08-19 10:34 UTC, olaszsoma commented on src/dreicer.cpp
> +		throw "Effective charge higher than 1";
Wrong message, fix it.

2020-08-19 10:34 UTC, olaszsoma commented on src/dreicer.cpp
> +		throw "Effective charge higher than 1";
Wrong message, fix it.

2020-08-19 11:47 UTC, olaszsoma approved these changes
Looks good, Gergo should review it.

2020-08-21 13:39 UTC, gergopokol commented on include/constants.h
> +    const double runaway_electron_lower_boundary = 0;
This might not be needed.

2020-08-21 13:40 UTC, pordaniel01 commented on include/constants.h
> +    const double runaway_electron_lower_boundary = 0;
This should be removed

2020-08-21 14:03 UTC, gergopokol commented on src/hdf5export.cpp
> +		cout << "  [Runaway Fluid] \tHDF5 output file: "  << FILE_NAME << endl;
`Runaway Fluid` to be renamed to `Runaway Physics` everywhere.

2020-08-21 14:12 UTC, gergopokol commented on test/tests.cpp
> +cell CELL = {reference_rho_tor_norm, reference_ne, reference_te, reference_Zeff_1,reference_electric_field_1_runafluid, reference_magnetic_field, reference_runaway_electron_density_before};
`reference_electric_field_1_runafluid` to be renamed to `reference_electric_field_2`. All references to runafluid are to be removed.

2020-08-21 14:22 UTC, gergopokol requested changes
Minor changes requested in comments. Plus #49 is to be finished.

2020-08-25 13:32 UTC, gergopokol approved these changes

2020-08-26 08:11 UTC, merged